# Generated by Django 4.0.4 on 2022-06-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DH_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send_data',
            name='keyword',
        ),
        migrations.AddField(
            model_name='send_data',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='send_data',
            name='title',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
