# Generated by Django 4.0.4 on 2022-06-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DH_service', '0004_send_data_end_day_send_data_start_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_data',
            name='text',
            field=models.TextField(max_length=10),
        ),
    ]
