# Generated by Django 4.0.4 on 2022-06-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DH_service', '0005_alter_send_data_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send_data',
            name='end_day',
        ),
        migrations.RemoveField(
            model_name='send_data',
            name='start_day',
        ),
        migrations.AlterField(
            model_name='send_data',
            name='text',
            field=models.TextField(),
        ),
    ]
