# Generated by Django 4.0.4 on 2022-06-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DH_service', '0006_remove_send_data_end_day_remove_send_data_start_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_data',
            name='end_day',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='send_data',
            name='start_day',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='send_data',
            name='text',
            field=models.CharField(max_length=10),
        ),
    ]
