# Generated by Django 4.0.4 on 2022-06-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DH_service', '0007_send_data_end_day_send_data_start_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_data',
            name='end_day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='send_data',
            name='start_day',
            field=models.DateField(),
        ),
    ]
